### ISSUE TITLE
feature request: config option to enable/disable report sections

### ISSUE THREAD

**Issue by csessh** [ptdewey/pendulum-nvim#10]
hey thanks for the fun plugin. I love the simplicity of it. It would make a banger dashboard too.

I would love to submit a PR to add more customization options:

1) what section to display. personally, I don't care for what branch I use the most, for example. 

for example: 
```
{
    section = {
        branch = false,
        files = true,
        directories = true,
        filetypes = true,
        projects = true,
    },
}
```

2) filetypes to exclude. `neo-tree` and `TelescopePrompt` really took no time to  take over the leader board.

**Comment by ptdewey** [comment]
Hello! I'm glad you like the plugin and I'd be happy to accept these changes if you made a PR. 

Most of the work would be on the go side (primarily in `remote/internal/metrics.go` and `remote/pkg/utils.go`), with some tweaks to the lua code to add new config options and pass them to the go process. 

I just finished a redesign of the rpc arguments that should make these changes substantially easier, so make sure to base your work off the dev branch.

Let me know if you have any questions, and I'm looking forward to seeing what you come up with!
