### ISSUE TITLE
Is Pendulum supposed to create the file?

### ISSUE THREAD

**Issue by JustBarnt** [ptdewey/pendulum-nvim#2]
Is pendulum supposed to automatically create the `csv` file or is it expected that we create it before?

If it's the latter, than this plugin is suffering from similar issues on Windows OS's where it is lacking the permissions to create the file at the path given.

**Comment by ptdewey** [comment]
Pendulum is supposed to create the file if it doesn't exist.
It is quite possible that it doesn't have permissions to create the file in Windows, but I'm not familiar enough with Windows to know how to immediately fix it, but I can look into it.

I've also realized there is an issue with the binrary path for the report on windows (the file has an .exe extension which is not currently handled.)

**Comment by ptdewey** [comment]
I attempted to fix this issue, if you could try installing the plugin targeting the 'dev' branch and let me know if the problem is still happening that would be great.

**Comment by JustBarnt** [comment]
@ptdewey Wow that was quick! Yeah I can take a look later today when my day slows down!

**Comment by JustBarnt** [comment]
@ptdewey Sorry I did not get back this quicker, unfortunately this did not work with the dev branch update.

This was the error given 

```
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: .../Local/nvim-data/lazy/pendulum-nvim/lua/pendulum/csv.lua:47: Error opening file: C:\\Users\\bwilliams\\.pendulum\\time_log.csv
stack traceback:
	[C]: in function 'error'
	.../Local/nvim-data/lazy/pendulum-nvim/lua/pendulum/csv.lua:47: in function 'write_table_to_csv'
	...l/nvim-data/lazy/pendulum-nvim/lua/pendulum/handlers.lua:74: in function 'log_activity'
	...l/nvim-data/lazy/pendulum-nvim/lua/pendulum/handlers.lua:116: in function <...l/nvim-data/lazy/pendulum-nvim/lua/pendulum/handlers.lua:115>
```
![image](https://github.com/user-attachments/assets/6488b51e-e87d-49e5-b749-4d1450fac9c3)

**Comment by ptdewey** [comment]
What does your config look like, and does the directory the plugin is trying to create the file in exist?

**Comment by JustBarnt** [comment]
No the directory in which the file is to be created does not exist, does it need to exist? I would have thought the directory would be created automatically if it did not exist.

Here is my config: 
```lua
{
 "ptdewey/pendulum-nvim",
 branch = "dev",
 opts = {
   log_file = vim.fn.expand("~/.pendulum/time_log.csv"),
   timeout_len = 300,
   timer_len = 60,
   top_n = 10,
 },
}
```

**Comment by JustBarnt** [comment]
I can confirm that if I just create the directory the file will get created. Would you consider it in scope of what you want this plugin to do, to create the directory as well if it doesn't exist?

**Comment by ptdewey** [comment]
I'll make it able to create directories when I get a chance.

**Comment by JustBarnt** [comment]
Awesome and thank you for you work on this plugin! It has become really useful for my time management!

**Comment by ptdewey** [comment]
I added directory creation to the dev branch in 764ac5c, please update and let me know if the issue persists. If everything is good, I will merge the changes into main.

**Comment by JustBarnt** [comment]
@ptdewey I can confirm the latest change on the dev branch does fix my issue!
