### ISSUE TITLE
feature request:  loaded plug-in time ranking

### ISSUE THREAD

**Issue by edte** [ptdewey/pendulum-nvim#5]

**Comment by ptdewey** [comment]
Can you elaborate a bit more about what you want to see added?

**Comment by edte** [comment]
use lazy.nvim to manage lazy loading. Want the loading status of the plug-in, can use it to determine which plugins are more commonly used and which are less commonly used.

**Comment by ptdewey** [comment]
I think this functionality is out of scope of what pendulum is supposed to be, and I'm not really sure how to keep track of when plugins are being actively used.
